spring:
  application:
    name: product-service

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      user-service: # Match the 'name' in your @FeignClient
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/